global:
  scrape_interval: 15s  # Define o intervalo global de coleta de métricas para 15 segundos

scrape_configs: 
  - job_name: 'techChallenge2'  # Nome do job para identificação
    scrape_interval: 5s  # Intervalo de coleta específico para este job (5 segundos)
    static_configs:
      - targets: ['webapi:8080']  # Endpoints a serem monitorados pelo Prometheus 
  - job_name: 'rabbitmq'
    static_configs:
      - targets: ['rabbitmq-exporter:9419']
