apiVersion: v1
kind: ConfigMap
metadata:
  name: webapi-config
data:
  ASPNETCORE_ENVIRONMENT: "Development"
  ConnectionStrings__SqlConnection: "Server=localhost,1433;Database=TechChallenge4;User ID=tech_challenge;Password=tech@2024;Trusted_Connection=False; TrustServerCertificate=true;"
  RabbitMq__Host: "localhost"
  RabbitMq__Username: "guest"
  RabbitMq__Password: "guest"
