apiVersion: v1
kind: Service
metadata:
  name: techchallenge-webapi-service
spec:
  type: NodePort
  selector:
    app: techchallenge-webapi-container
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30000  # Ou outra porta entre 30000-32767
      
---
apiVersion: v1
kind: Service
metadata:
  name: techchallenge-application-service
spec:
  type: ClusterIP
  selector:
    app: techchallenge-apllication-container