apiVersion: v1
kind: Service
metadata:
  name: techchallenge4-service
spec:
  type: NodePort
  selector:
    app: techchallenge4  
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30000  # Ou outra porta entre 30000-32767
