apiVersion: v1
kind: Service
metadata:
  name: sqlserver-service
spec:
  selector:
    app: sqlserver
  ports:
    - protocol: TCP
      name: tcp3
      port: 1433
      targetPort: 1433
      nodePort: 31433
  type: NodePort
