name: Build, test, and deploy to Kubernetes

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  deploy-to-kubernetes:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4

      - name: Set up kubectl
        env:
          KUBECONFIG_DATA: ${{ secrets.KUBECONFIG_DATA }}
        run: |
          # Decode the kubeconfig data using PowerShell
          $decodedKubeconfig = [System.Text.Encoding]::UTF8.GetString([Convert]::FromBase64String("${{ env.KUBECONFIG_DATA }}"))
          if ($decodedKubeconfig) {
              echo "Kubeconfig decodificado com sucesso:"
              echo $decodedKubeconfig
          } else {
              echo "Falha ao decodificar o kubeconfig."
              exit 1
          }
          $decodedKubeconfig | Out-File -FilePath kubeconfig -Encoding UTF8

          # Set the kubeconfig environment variable
          $env:KUBECONFIG = ".\kubeconfig"

          # Test kubectl connectivity
          kubectl cluster-info

      - name: Deploy FrontEnd to Kubernetes
        shell: powershell
        run: |
          $env:KUBECONFIG = "$PWD\kubeconfig"
          kubectl config use-context docker-desktop
          kubectl apply -k .\Kubernetes\frontend

      - name: Deploy API to Kubernetes
        shell: powershell
        run: |
          kubectl apply -k ./Kubernetes/webapi

      - name: Deploy Another Service to Kubernetes
        shell: powershell
        run: |
          kubectl apply -k ./Kubernetes/application
